name: Feature Request
description: Suggest a new feature or enhancement for sidepanel-fallback
title: '[Feature] '
labels: ['enhancement', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible about your idea.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New API method
        - Enhancement to existing functionality
        - Performance improvement
        - Developer experience improvement
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
      placeholder: 'I would like to see...'
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If this involves new API methods or changes, describe the proposed API.
      render: javascript
      placeholder: |
        // Example of proposed API
        SidepanelFallback.newMethod({
          option1: 'value',
          option2: true
        });

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "I've considered..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Blocking my project
    validations:
      required: true

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would implementing this feature require breaking changes to the existing API?
      options:
        - 'No, this would not require breaking changes'
        - 'Yes, this would require breaking changes'
        - "I'm not sure"
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be beneficial.
      placeholder: |
        1. When building a Chrome extension that...
        2. For developers who need to...
        3. In scenarios where...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: 'Any additional information, links to related projects, screenshots, etc.'

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to implementing this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I can help with testing the implementation
        - label: I can help with documentation
